### ISSUE TITLE
stat command problems

### ISSUE THREAD

**Issue by mdi** [technopagan/adept-jpg-compressor#32]
Since the merge of #31, I'm seeing errors like below:

```
stat: cannot read file system information for '\'%z\'': No such file or directory
./bin/adept.sh: line 181: File:: command not found
```

I do have GNU stat installed.

**Comment by technopagan** [comment]
My apologies! This was due to merging pull requests which caused this error to appear. I've reverted the repository to a stable state now. Please be aware that - inspired by Adept - mozjpeg will gain adaptive compression on a per-block level very soon - at which point this repository will no longer be maintained & I will encourage you all to switch to mozjpeg completely.
